language: php

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
  include:
    - php: 5.6
      env: ES_VERSION="1.6.2"
    - php: 5.6
      env: ES_VERSION="1.5.2"
    - php: 5.6
      env: ES_VERSION="1.4.5"
    - php: 5.6
      env: ES_VERSION="1.3.9"
    - php: 5.6
      env: ES_VERSION="1.2.4"
    - php: 5.6
      env: ES_VERSION="1.1.2"
    - php: 5.6
      env: ES_VERSION="1.0.3"

env:
  global:
    - ES_VERSION="1.7.1"
    - ES_TEST_HOST=http://localhost:9200

before_install:
  - curl -L -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.zip
  - unzip elasticsearch-$ES_VERSION.zip
  - elasticsearch-$ES_VERSION/bin/elasticsearch
  - sleep 3 # wait till Elastic completely starts

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then php vendor/bin/coveralls; fi
