language: php

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: ES_VERSION="1.6.2"
    - php: 5.6
      env: ES_VERSION="1.5.2"
    - php: 5.6
      env: ES_VERSION="1.4.5"
    - php: 5.6
      env: ES_VERSION="1.3.9"

env:
  global:
    - ES_VERSION="1.7.1"
    - ES_TEST_HOST=http://localhost:9200

before_install:
  - ./travis/download_run_es.sh

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
