language: php

branches:
  except:
    - 0.4

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm


env:
  global:
    - ES_VERSION="master"
    - TEST_BUILD_REF="origin/master"
    - ES_TEST_HOST=http://localhost:9200

before_install:
  - ./travis/download_and_run_es.sh

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi
  - php util/RestSpecRunner.php
  - php util/EnsureClusterAlive.php

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
