name: PHP test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1]
        os: [ubuntu-latest]
        es-version: [8.0.0-SNAPSHOT]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: yaml, zip, curl
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: |
        composer install --prefer-dist

    - name: PHP Static Analysis Tool
      run: |
        composer run-script phpstan

    - name: Unit tests
      run: |
        vendor/bin/phpunit -c phpunit.xml.dist
      env:
        TEST_SUITE: free
        